### ISSUE TITLE
please add example db.json from db-prices-radar

### ISSUE THREAD

**Issue by mapl** [derhuerst/db-prices-viz#3]

**Comment by derhuerst** [comment]
Sorry, I won't add recorded data here, since DB is pretty sensitive regarding publishing recorded prices & delays.

But maybe we can get `db-prices-radar` and this repo working again. Keep in mind though that this is an outdated hackathon project, which we currently don't intend to maintain.

What do you want to do?

**Comment by mapl** [comment]
ah I see, make sense. "db-prices-radar" is producing a valid json file, at least under linux :) Windows doesn't like colons ":" in the filename. I have issues getting an output at all from running example.js when using a recent json file from "db-prices-radar". would be really nice to have all 3 components (radar,viz,viz-web) in a working condition again.

**Comment by derhuerst** [comment]
What do you want to do?

**Comment by mapl** [comment]
No big goals here. I want to track how the price develops over time as its inital intention was I guess

**Comment by derhuerst** [comment]
The reason I asked is because often people want to do slightly different things, and there are a lot of other tools out there that we wrote ([here](https://github.com/juliuste?utf8=✓&tab=repositories&q=db&type=&language=) and [here](https://github.com/derhuerst?utf8=✓&tab=repositories&q=db&type=&language=)) that might be more appropriate.

Regarding your actual point:

- **We should make `db-prices-radar` work again.** Maybe @juliuste is willing to upgrade it to `db-prices@latest`.
- Looking further into the future, I think it might sense to have a tool like [`record-vbb-delays`](https://github.com/derhuerst/record-vbb-delays), but for Deutsche Bahn and for prices.

**Comment by derhuerst** [comment]
closing in favour of juliuste/db-prices-radar#1.
